const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
const pid=new URLSearchParams(location.search).get('project'); let state=null;
const preview=document.getElementById('preview'), panel=document.getElementById('panel');
async function api(url,opt={}){opt.headers={'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(opt.headers||{})};const r=await fetch(url,opt); if(!r.ok)throw new Error(await r.text()); return r.json();}
async function load(){state=await api('/api/project/'+pid); renderUI(); await refresh();}
async function refresh(){const r=await api('/api/render/'+pid,{method:'POST',body:JSON.stringify(state)}); preview.src=r.url+'?t='+Date.now();}
function renderUI(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));showTab('text');}
function showTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); if(tab==='text') textPanel(); if(tab==='image') imagePanel(); if(tab==='style') stylePanel(); if(tab==='layout') layoutPanel();}
function row(label,html){return `<div class="row"><label>${label}</label>${html}</div>`}
function textPanel(){panel.innerHTML=row('Title',`<input id="title" type="text" value="${esc(state.title)}">`)+row('Subtitle',`<input id="subtitle" type="text" value="${esc(state.subtitle||'')}">`)+row('Synopsis',`<textarea id="syn" rows="7">${esc(state.synopsis)}</textarea>`)+row('Rating',`<input id="rating" type="number" min="0" max="10" step="0.1" value="${Number(state.rating||0).toFixed(1)}">`)+row('Season',`<input id="season" type="text" value="${esc(state.season_text||'')}">`)+row('Genres',`<input id="genres" type="text" value="${esc((state.genres||[]).join(', '))}">`)+`<div class="control"><button id="applyText">Apply</button></div>`; document.getElementById('applyText').onclick=async()=>{state.title=document.getElementById('title').value;state.subtitle=document.getElementById('subtitle').value;state.synopsis=document.getElementById('syn').value;state.rating=+document.getElementById('rating').value||0;state.season_text=document.getElementById('season').value||null;state.genres=document.getElementById('genres').value.split(',').map(x=>x.trim()).filter(Boolean);await saveRender();};}
function imagePanel(){let l=state.layout;panel.innerHTML=row('Background zoom',`<input id="bz" type="range" min="1" max="2" step=".05" value="${l.background_zoom||1}">`)+row('Top image zoom',`<input id="tz" type="range" min=".7" max="2" step=".05" value="${l.top_zoom||1}">`)+row('Card images zoom',`<input id="cz" type="range" min=".7" max="2" step=".05" value="${l.card_zoom||1}">`)+`<div class="control"><button id="applyImg">Apply</button></div>`;document.getElementById('applyImg').onclick=async()=>{l.background_zoom=+document.getElementById('bz').value;l.top_zoom=+document.getElementById('tz').value;l.card_zoom=+document.getElementById('cz').value;await saveRender();};}
function stylePanel(){panel.innerHTML=row('Accent',`<div style="padding:10px 0">Automatically extracted from the main artwork.</div>`)+row('Watermark',`<input id="wm" type="text" value="${esc(state.watermark||'@Ongoing_english_dub')}">`)+`<div class="control"><button id="applyStyle">Apply</button></div>`;document.getElementById('applyStyle').onclick=async()=>{state.watermark=document.getElementById('wm').value||'@Ongoing_english_dub';await saveRender();};}
function layoutPanel(){let l=state.layout;panel.innerHTML=row('Background focal X',`<input id="bx" type="range" min="0" max="1" step=".01" value="${l.background_focal?.[0]??.5}">`)+row('Background focal Y',`<input id="by" type="range" min="0" max="1" step=".01" value="${l.background_focal?.[1]??.5}">`)+row('Top focal X',`<input id="tx" type="range" min="0" max="1" step=".01" value="${l.top_focal?.[0]??.5}">`)+row('Top focal Y',`<input id="ty" type="range" min="0" max="1" step=".01" value="${l.top_focal?.[1]??.5}">`)+`<div class="control"><button id="applyLayout">Apply</button><button id="reset">Reset</button></div>`;document.getElementById('applyLayout').onclick=async()=>{l.background_focal=[+bx.value,+by.value];l.top_focal=[+tx.value,+ty.value];await saveRender();};document.getElementById('reset').onclick=async()=>{state=await api('/api/project/'+pid+'/reset',{method:'POST',body:JSON.stringify({})});renderUI();await refresh();};}
async function saveRender(){await api('/api/project/'+pid,{method:'PUT',body:JSON.stringify(state)});await refresh();}
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=async()=>{const r=await fetch('/api/export/'+b.dataset.export+'/'+pid,{headers:{'X-Telegram-Init-Data':tg?.initData||''}});if(!r.ok)return alert(await r.text());const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.title+'.'+b.dataset.export;a.click();URL.revokeObjectURL(a.href);});document.getElementById('save').onclick=async()=>{await api('/api/project/'+pid,{method:'PUT',body:JSON.stringify(state)});tg?.close();};document.getElementById('back').onclick=()=>tg?.close();function esc(s){return String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}load().catch(e=>{document.body.innerHTML='<p style="padding:20px">Editor failed: '+e.message+'</p>'});
