const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
const pid=new URLSearchParams(location.search).get('project'); let state=null; let dirty=false;
const preview=document.getElementById('preview'), panel=document.getElementById('panel');
async function api(url,opt={}){opt.headers={'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(opt.headers||{})};const r=await fetch(url,opt); if(!r.ok)throw new Error(await r.text()); return r.json();}
async function load(){state=await api('/api/project/'+pid); renderUI(); await refresh();}
async function refresh(){const r=await api('/api/render/'+pid,{method:'POST',body:JSON.stringify(state)}); preview.src=r.url+'?t='+Date.now(); dirty=false;}
function renderUI(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));showTab('text');}
function showTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); if(tab==='text') textPanel(); if(tab==='image') imagePanel(); if(tab==='style') stylePanel(); if(tab==='layout') layoutPanel();}
function row(label,html){return `<div class="row"><label>${label}</label>${html}</div>`}
function textPanel(){panel.innerHTML=row('Title',`<input id="title" type="text" value="${esc(state.title)}">`)+row('Synopsis',`<textarea id="syn" rows="7">${esc(state.synopsis)}</textarea>`)+row('Season',`<input id="season" type="text" value="${esc(state.season_text||'')}">`)+`<div class="control"><button id="applyText">Apply</button></div>`; document.getElementById('applyText').onclick=async()=>{state.title=document.getElementById('title').value;state.synopsis=document.getElementById('syn').value;state.season_text=document.getElementById('season').value||null;await saveRender();};}
function imagePanel(){let l=state.layout,c=l.circle;panel.innerHTML=row('Circle zoom',`<input id="cz" type="range" min=".6" max="1.8" step=".05" value="${c.zoom||1}">`)+row('Background zoom',`<input id="bz" type="range" min="1" max="2" step=".05" value="${l.background_zoom||1}">`)+row('Poster zoom',`<input id="pz" type="range" min=".7" max="2" step=".05" value="${l.poster_zoom||1}">`)+`<div class="control"><button id="applyImg">Apply</button></div>`;document.getElementById('applyImg').onclick=async()=>{c.zoom=+document.getElementById('cz').value;l.background_zoom=+document.getElementById('bz').value;l.poster_zoom=+document.getElementById('pz').value;await saveRender();};}
function stylePanel(){panel.innerHTML=row('Overlay opacity',`<input id="op" type="range" min="20" max="210" value="${state.layout.overlay_opacity||120}">`)+row('Panel opacity',`<input id="pp" type="range" min="0" max="220" value="${state.layout.panel?.fill?.[3]??125}">`)+`<div class="control"><button id="applyStyle">Apply</button></div>`;document.getElementById('applyStyle').onclick=async()=>{state.layout.overlay_opacity=+document.getElementById('op').value;state.layout.panel.fill[3]=+document.getElementById('pp').value;await saveRender();};}
function layoutPanel(){let c=state.layout.circle,p=state.layout.panel,t=state.layout.title,s=state.layout.synopsis;panel.innerHTML=row('Circle position X',`<input id="cx" type="range" min="450" max="1050" value="${c.x}">`)+row('Circle position Y',`<input id="cy" type="range" min="180" max="540" value="${c.y}">`)+row('Circle size',`<input id="cs" type="range" min="280" max="520" value="${c.size}">`)+row('Title Y',`<input id="ty" type="range" min="20" max="180" value="${t.y}">`)+row('Synopsis Y',`<input id="sy" type="range" min="180" max="400" value="${s.y}">`)+`<div class="control"><button id="applyLayout">Apply</button><button id="reset">Reset</button></div>`;document.getElementById('applyLayout').onclick=async()=>{c.x=+cx.value;c.y=+cy.value;c.size=+cs.value;t.y=+ty.value;s.y=+sy.value;await saveRender();};document.getElementById('reset').onclick=async()=>{state=await api('/api/project/'+pid+'/reset',{method:'POST',body:JSON.stringify({})});renderUI();await refresh();};}
async function saveRender(){await api('/api/project/'+pid,{method:'PUT',body:JSON.stringify(state)});await refresh();}
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=async()=>{const r=await fetch('/api/export/'+b.dataset.export+'/'+pid,{headers:{'X-Telegram-Init-Data':tg?.initData||''}});if(!r.ok)return alert(await r.text());const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.title+'.'+b.dataset.export;a.click();URL.revokeObjectURL(a.href);});document.getElementById('save').onclick=async()=>{await api('/api/project/'+pid,{method:'PUT',body:JSON.stringify(state)});tg?.close();};document.getElementById('back').onclick=()=>tg?.close();function esc(s){return String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}load().catch(e=>{document.body.innerHTML='<p style="padding:20px">Editor failed: '+e.message+'</p>'});
