const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
const pid=new URLSearchParams(location.search).get('project'); let state=null;
const preview=document.getElementById('preview'), panel=document.getElementById('panel');
async function api(url,opt={}){opt.headers={'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(opt.headers||{})};const r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text());return r.json();}
async function load(){state=await api('/api/project/'+pid);renderUI();await refresh();}
async function refresh(){const r=await api('/api/render/'+pid,{method:'POST',body:JSON.stringify(state)});preview.src=r.url+'?t='+Date.now();}
function renderUI(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));showTab('text');}
function showTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='text')textPanel();if(tab==='image')imagePanel();if(tab==='style')stylePanel();if(tab==='layout')layoutPanel();}
function row(label,html){return `<div class="row"><label>${label}</label>${html}</div>`}
function textPanel(){panel.innerHTML=row('Title',`<input id="title" value="${esc(state.title)}">`)+row('Subtitle',`<input id="subtitle" value="${esc(state.subtitle||'')}">`)+row('Synopsis',`<textarea id="syn" rows="7">${esc(state.synopsis)}</textarea>`)+row('Season / year',`<input id="season" value="${esc(state.season_text||'')}">`)+row('Genres',`<input id="genres" value="${esc((state.genres||[]).join(', '))}">`)+row('Rating',`<input id="rating" type="number" step="0.1" min="0" max="10" value="${state.rating??''}">`)+`<div class="control"><button id="applyText">Apply</button></div>`;document.getElementById('applyText').onclick=async()=>{state.title=title.value;state.subtitle=subtitle.value;state.synopsis=syn.value;state.season_text=season.value||null;state.genres=genres.value.split(',').map(x=>x.trim()).filter(Boolean);state.rating=rating.value===''?null:+rating.value;await saveRender();};}
function imagePanel(){let l=state.layout,t=l.top_image,c1=l.card1,c2=l.card2;panel.innerHTML=row('Background zoom',`<input id="bz" type="range" min="1" max="2" step=".05" value="${l.background_zoom||1}">`)+row('Top image zoom',`<input id="tz" type="range" min=".7" max="2" step=".05" value="${t.zoom||1}">`)+row('Card 1 zoom',`<input id="c1z" type="range" min=".7" max="2" step=".05" value="${c1.zoom||1}">`)+row('Card 2 zoom',`<input id="c2z" type="range" min=".7" max="2" step=".05" value="${c2.zoom||1}">`)+`<div class="control"><button id="applyImg">Apply</button></div>`;applyImg.onclick=async()=>{l.background_zoom=+bz.value;t.zoom=+tz.value;c1.zoom=+c1z.value;c2.zoom=+c2z.value;await saveRender();};}
function stylePanel(){panel.innerHTML=row('Accent',`<input value="${rgbHex(state.accent_color)}" disabled><small>Automatically extracted from the main image.</small>`)+row('Panel opacity',`<input id="po" type="range" min="20" max="230" value="${Math.round((state.layout.info_panel?.opacity??155))}">`)+`<div class="control"><button id="applyStyle">Apply</button></div>`;applyStyle.onclick=async()=>{state.layout.info_panel.opacity=+po.value;await saveRender();};}
function layoutPanel(){let l=state.layout,t=l.top_image,c1=l.card1,c2=l.card2,p=l.info_panel,s=l.synopsis;panel.innerHTML=row('Top image X',`<input id="tx" type="range" min="0" max="100" value="${t.x}">`)+row('Top image Y',`<input id="ty" type="range" min="80" max="250" value="${t.y}">`)+row('Card X',`<input id="cx" type="range" min="560" max="820" value="${c1.x}">`)+row('Panel X',`<input id="px" type="range" min="700" max="900" value="${p.x}">`)+row('Panel Y',`<input id="py" type="range" min="380" max="500" value="${p.y}">`)+`<div class="control"><button id="applyLayout">Apply</button><button id="reset">Reset</button></div>`;applyLayout.onclick=async()=>{t.x=+tx.value;t.y=+ty.value;c1.x=+cx.value;c2.x=+cx.value;p.x=+px.value;p.y=+py.value;await saveRender();};reset.onclick=async()=>{state=await api('/api/project/'+pid+'/reset',{method:'POST'});renderUI();await refresh();};}
async function saveRender(){await api('/api/project/'+pid,{method:'PUT',body:JSON.stringify(state)});await refresh();}
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=async()=>{const r=await fetch('/api/export/'+b.dataset.export+'/'+pid,{headers:{'X-Telegram-Init-Data':tg?.initData||''}});if(!r.ok)return alert(await r.text());const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.title+'.'+b.dataset.export;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);});document.getElementById('save').onclick=async()=>{await api('/api/project/'+pid,{method:'PUT',body:JSON.stringify(state)});tg?.close();};document.getElementById('back').onclick=()=>tg?.close();function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}function rgbHex(c){return '#'+(c||[0,0,0]).map(x=>Number(x).toString(16).padStart(2,'0')).join('')}
load().catch(e=>{document.body.innerHTML='<p style="padding:20px">Editor failed: '+e.message+'</p>'});
